
import { ConsentRequestDto, ConsentRightDto } from "../../../../clients/access-management/consent-enterprise/consent-enterprise.types.js";
import { ConsentRequestBuilder, EnterpriseClient } from "../../../../clients/access-management/consent-enterprise/index.js";
import { ConsentLookupRequestBuilder, MaskinportenClient } from "../../../../clients/access-management/resource-owner/maskinporten/index.js";
import { ConsentLookupRequest } from "../../../../clients/access-management/resource-owner/maskinporten/maskinporten.types.js";
import { ConsentClient } from "../../../../clients/access-management-bff/consent/index.js";
import { EnterpriseTokenBuilder, EnterpriseTokenGenerator, PersonalTokenBuilder, PersonalTokenGenerator } from "../../../../common-imports.js";
import { fetchTestData } from "../../../../helpers.js";
import { AltinnScopes, CreateScopeString } from "../../../../scopes.js";

/**
 * The consentee organizations and consenter persons are kept in CSV files, one
 * per environment, so that a test can spread its consents across many
 * organizations and persons instead of hammering one of each.
 *
 * Test data folder (one folder per use case, one file per environment):
 * K6/testdata/access-management/consent
 * - consentee-orgs/<env>.csv       (header: orgNo)
 * - consenter-persons/<env>.csv    (header: ssn,partyUuid)
 * - lookup/<env>.csv               (header: Pid,Org,ConsentId)
 */

/**
 * The resource the generated consents are for.
 */
export const CONSENT_RESOURCE = "samtykke-performance-test";

/**
 * How long the consents the tests create stay valid, and how long the ones the lookup
 * test data is generated from stay valid. See {@link consentValidTo} and
 * {@link lookupConsentValidTo} for why the two differ.
 */
const CONSENT_VALID_DAYS = 14;
const LOOKUP_CONSENT_VALID_DAYS = 1520;

/**
 * Where the consenter is sent after handling the consent request.
 */
const REDIRECT_URL = "https://altinn.no";

/**
 * @type {object | undefined}
 */
let clients = undefined;

/**
 * @type {EnterpriseTokenGenerator | undefined}
 */
let consenteeTokenGenerator = undefined;

/**
 * @type {PersonalTokenGenerator | undefined}
 */
let consenterTokenGenerator = undefined;

/**
 * @type {EnterpriseClient | undefined}
 */
let eventsClient = undefined;

/**
 * @type {EnterpriseTokenGenerator | undefined}
 */
let eventsTokenGenerator = undefined;

/**
 * @type {MaskinportenClient | undefined}
 */
let lookupClient = undefined;

/**
 * The organizations that receive, and therefore hold, the consents.
 *
 * @param {string} env - Environment, e.g. "yt01".
 * @returns {Array<{orgNo: string}>} The consentee organizations.
 */
export function getConsenteeOrgs(env) {
    return fetchTestData(`access-management/consent/consentee-orgs/${env}.csv`);
}

/**
 * The persons that approve the consents.
 *
 * @param {string} env - Environment, e.g. "yt01".
 * @returns {Array<{ssn: string, partyUuid: string}>} The consenter persons.
 */
export function getConsenterPersons(env) {
    return fetchTestData(`access-management/consent/consenter-persons/${env}.csv`);;
}

/**
 * Consents generated by an earlier run of testdataGeneration/consent-data.js,
 * for the lookup test to look up.
 *
 * @param {string} env - Environment, e.g. "yt01".
 * @returns {Array<{Pid: string, Org: string, ConsentId: string}>} Consents to look up.
 */
export function getLookupConsents(env) {
    return fetchTestData(`access-management/consent/lookup/${env}.csv`);;;
}

/**
 * Creates and caches the clients the consent lifecycle uses.
 *
 * Built once per VU and reused across its iterations. The token generators cache
 * tokens per instance, so building them per iteration refetches every token from
 * the token generator service each time.
 *
 * Both identities change per iteration, unlike the system user tests where only
 * the approver does: the consentee is the organization the consent is given to and
 * the consenter is the person giving it. Both are swapped with
 * setTokenGeneratorOptions rather than by building new generators, so both
 * generators come back. The cache is keyed on the options, so each identity still
 * gets its own cached token.
 *
 * The consentee token carries the read scope alongside the write scope, which is
 * what lets a test confirm the consent request it made was accepted.
 *
 * Handling a consent request is what the person does in the portal, so it goes
 * through the bff rather than the enterprise api the organization calls.
 *
 * @returns {[any, EnterpriseTokenGenerator, PersonalTokenGenerator]} Clients grouped by who they act as, and the two token generators.
 */
export function getClients() {
    if (clients === undefined) {
        consenteeTokenGenerator = new EnterpriseTokenGenerator(
            getConsenteeTokenOpts(),
        );

        consenterTokenGenerator = new PersonalTokenGenerator(
            getConsenterTokenOpts(),
        );

        clients = {
            consentee: {
                enterpriseClient: new EnterpriseClient(__ENV.BASE_URL, consenteeTokenGenerator),
            },
            consenter: {
                consentClient: new ConsentClient(__ENV.AM_UI_BASE_URL, consenterTokenGenerator),
            },
        };
    }

    return [clients, consenteeTokenGenerator, consenterTokenGenerator];
}

/**
 * Creates and caches the client the events test reads with.
 *
 * A narrower token than getClients: that test only reads the events of an existing
 * organization, so it asks for nothing beyond the read scope. Keeping it apart also
 * keeps the events test off AM_UI_BASE_URL, which it has no use for.
 *
 * Cached at module scope, so a VU builds it once and keeps the token it fetched
 * rather than refetching on every iteration.
 *
 * @returns {[EnterpriseClient, EnterpriseTokenGenerator]} The client, and the generator whose organization is swapped per iteration.
 */
export function getEventsClient() {
    if (eventsClient === undefined) {
        eventsTokenGenerator = new EnterpriseTokenGenerator(
            getEventsTokenOpts(),
        );

        eventsClient = new EnterpriseClient(__ENV.BASE_URL, eventsTokenGenerator);
    }

    return [eventsClient, eventsTokenGenerator];
}

/**
 * Creates and caches the client the lookup test reads with.
 *
 * Kept apart from getClients because it needs its own token: the lookup is what
 * Maskinporten does on behalf of the consumer, so it asks for the Maskinporten
 * consent scope and nothing else.
 *
 * The token carries no organization number, matching how the endpoint is called
 * in practice.
 *
 * @returns {MaskinportenClient} The client the lookup test reads with.
 */
export function getLookupClient() {
    if (lookupClient === undefined) {
        const tokenGenerator = new EnterpriseTokenGenerator(
            new EnterpriseTokenBuilder()
                .withEnvironment(__ENV.ENVIRONMENT)
                .withTtl(3600)
                .withScopes(CreateScopeString([AltinnScopes.MASKINPORTEN.CONSENT.READ]))
                .build(),
        );

        lookupClient = new MaskinportenClient(__ENV.BASE_URL, tokenGenerator);
    }

    return lookupClient;
}

/**
 * Token options for acting as the organization a consent is given to.
 *
 * Called without an organization number to build the generator, and with one per
 * iteration to point it at the organization that iteration drew.
 *
 * @param {string} [orgNo] - The consentee organization, or undefined to leave the token without one.
 * @returns Options to hand to setTokenGeneratorOptions.
 */
export function getConsenteeTokenOpts(orgNo = undefined) {
    const builder = new EnterpriseTokenBuilder()
        .withEnvironment(__ENV.ENVIRONMENT)
        .withTtl(3600)
        .withScopes(CreateScopeString([
            AltinnScopes.CONSENTREQUESTS.WRITE,
            AltinnScopes.CONSENTREQUESTS.READ,
        ]));

    if (orgNo !== undefined) {
        builder.withOrganizationNumber(orgNo);
    }

    return builder.build();
}

/**
 * Token options for reading the events of an organization.
 *
 * Called without an organization number to build the generator, and with one per
 * iteration to point it at the organization that iteration drew.
 *
 * @param {string} [orgNo] - The organization, or undefined to leave the token without one.
 * @returns Options to hand to setTokenGeneratorOptions.
 */
export function getEventsTokenOpts(orgNo = undefined) {
    const builder = new EnterpriseTokenBuilder()
        .withEnvironment(__ENV.ENVIRONMENT)
        .withTtl(3600)
        .withScopes(CreateScopeString([AltinnScopes.CONSENTREQUESTS.READ]));

    if (orgNo !== undefined) {
        builder.withOrganizationNumber(orgNo);
    }

    return builder.build();
}

/**
 * Token options for acting as the person giving a consent.
 *
 * Called without a party uuid to build the generator, and with one per iteration
 * to point it at the person that iteration drew.
 *
 * @param {string} [partyUuid] - The consenter, or undefined to leave the token without one.
 * @returns Options to hand to setTokenGeneratorOptions.
 */
export function getConsenterTokenOpts(partyUuid = undefined) {
    const builder = new PersonalTokenBuilder()
        .withEnvironment(__ENV.ENVIRONMENT)
        .withTtl(3600)
        .withScopes(CreateScopeString([AltinnScopes.PORTAL.ENDUSER]));

    if (partyUuid !== undefined) {
        builder.withPartyUuid(partyUuid);
    }

    return builder.build();
}

/**
 * Builds the consent request one iteration asks for.
 *
 * The id is generated by the caller rather than here, since the caller needs it
 * both to create the consent request and to look the consent up afterwards.
 *
 * @param {object} options - The parties and the id this consent request is for.
 * @param {string} options.consentId - The id the consent gets.
 * @param {string} options.from - Party urn of the person giving the consent.
 * @param {string} options.to - Party urn of the organization receiving it.
 * @param {string} [options.validTo] - When the consent expires, defaulting to {@link consentValidTo}.
 * @returns {ConsentRequestDto} The consent request payload.
 */
export function createConsentRequest({ consentId, from, to, validTo = consentValidTo() }) {
    return new ConsentRequestBuilder()
        .WithId(consentId)
        .WithFrom(from)
        .WithTo(to)
        .WithValidTo(validTo)
        .WithConsentRights(consentRights())
        .WithRedirectUrl(REDIRECT_URL)
        .Build();
}

/**
 * Builds the body that looks a consent up the way Maskinporten does.
 *
 * @param {object} options - The consent to look up.
 * @param {string} options.consentId - Id of the consent.
 * @param {string} options.from - Party urn of the person who gave the consent.
 * @param {string} options.to - Party urn of the organization that received it.
 * @returns {ConsentLookupRequest} The lookup payload.
 */
export function createConsentLookupRequest({ consentId, from, to }) {
    return new ConsentLookupRequestBuilder()
        .withId(consentId)
        .withFrom(from)
        .withTo(to)
        .build();
}

/**
 * The rights every generated consent covers.
 *
 * @returns {Array<ConsentRightDto>} The consent rights.
 */
export function consentRights() {
    return [
        {
            action: ["consent"],
            resource: [
                { type: "urn:altinn:resource", value: CONSENT_RESOURCE },
            ],
            metaData: { inntektsaar: "2026" },
        },
    ];
}

/**
 * Party urn of a person, as the consent api identifies the one giving a consent.
 *
 * @param {string} ssn - National identity number.
 * @returns {string} The party urn.
 */
export function personUrn(ssn) {
    return `urn:altinn:person:identifier-no:${ssn}`;
}

/**
 * Party urn of an organization, as the consent api identifies the one receiving a
 * consent.
 *
 * @param {string} orgNo - Organization number.
 * @returns {string} The party urn.
 */
export function organizationUrn(orgNo) {
    return `urn:altinn:organization:identifier-no:${orgNo}`;
}

/**
 * `validTo` for the consents the lifecycle test creates.
 *
 * Short on purpose: every iteration of post-consent.js leaves a consent behind, and
 * with a long validity the active consents and the consent log of the persons in the
 * rotation grow with every run until reading them says more about the pile than about
 * the endpoint. Two weeks is long enough that a consent outlives the run that made it,
 * short enough that the pile is bounded by the last two weeks of runs.
 *
 * @returns {string} Iso timestamp two weeks from now.
 */
export function consentValidTo() {
    return isoDaysFromNow(CONSENT_VALID_DAYS);
}

/**
 * `validTo` for the consents testdataGeneration/consent-data.js creates.
 *
 * These are generated once and committed as the lookup test data, so they have to
 * outlive many runs. The pile they leave behind is bounded by how often the data is
 * regenerated, not by how often the tests run.
 *
 * @returns {string} Iso timestamp roughly four years from now.
 */
export function lookupConsentValidTo() {
    return isoDaysFromNow(LOOKUP_CONSENT_VALID_DAYS);
}

/**
 * @param {number} days - How far ahead the timestamp should point.
 * @returns {string} Iso timestamp that many days from now.
 */
function isoDaysFromNow(days) {
    return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}
