import runConsentRequestEvents from "./consent-request-events.js";
import { setup as setupConsentRequestEvents } from "./consent-request-events.js";
import runLookup from "./lookup.js";
import { setup as setupLookup } from "./lookup.js";
import runPostConsent from "./post-consent.js";
import { setup as setupPostConsent } from "./post-consent.js";

/**
 * k6 setup stage. Runs each test's own setup and keeps the results apart.
 *
 * The three tests read different test data: the lifecycle test needs the
 * organizations and the persons, the events test only the organizations, and the
 * lookup test the consents an earlier generator run produced.
 *
 * @returns One entry per test that needs setup data.
 */
export function setup() {
    return {
        postConsent: setupPostConsent(),
        consentRequestEvents: setupConsentRequestEvents(),
        lookup: setupLookup(),
    };
}

/**
 * Runs every consent test in sequence, so a change to the shared consent clients
 * or building blocks can be verified with one k6 run instead of three.
 *
 * The lookup test reads consents generated by testdataGeneration/consent-data.js,
 * which only exists for yt01, so run this against yt01. The other two also pass on
 * at23 and tt02.
 *
 * @param {ReturnType<typeof setup>} data Setup results, keyed per test.
 */
export default function (data) {
    runPostConsent(data.postConsent);
    runConsentRequestEvents(data.consentRequestEvents);
    runLookup(data.lookup);
}

export { handleSummary } from "../../../../common-imports.js";
