import http from "k6/http";

import { ConsentRequestBuilder, EnterpriseClient } from "../../../../clients/access-management/consent-enterprise/index.js";
import { ConsentLookupRequestBuilder, MaskinportenClient } from "../../../../clients/access-management/resource-owner/maskinporten/index.js";
import { ConsentClient } from "../../../../clients/access-management-bff/consent/index.js";
import { EnterpriseTokenBuilder, EnterpriseTokenGenerator, PersonalTokenBuilder, PersonalTokenGenerator } from "../../../../common-imports.js";
import { parseCsvData } from "../../../../helpers.js";
import { AltinnScopes, CreateScopeString } from "../../../../scopes.js";

/**
 * The consentee organizations and consenter persons are kept in CSV files, one
 * per environment, so that a test can spread its consents across many
 * organizations and persons instead of hammering one of each.
 *
 * Test data folder (one folder per use case, one file per environment):
 * K6/testdata/authentication/consent/
 * - consentee-orgs/<env>.csv       (header: orgNo)
 * - consenter-persons/<env>.csv    (header: ssn,partyUuid)
 * - lookup/<env>.csv               (header: Pid,Org,ConsentId)
 */
const TESTDATA_BASE_URL =
    "https://raw.githubusercontent.com/Altinn/altinn-platform-validation-tests/refs/heads/main/K6/testdata/authentication/consent";

/**
 * The resource the generated consents are for.
 */
export const CONSENT_RESOURCE = "samtykke-performance-test";

/**
 * Where the consenter is sent after handling the consent request.
 */
const REDIRECT_URL = "https://altinn.no";

/**
 * @type {EnterpriseClient | undefined}
 */
let consenteeClient = undefined;

/**
 * @type {EnterpriseTokenGenerator | undefined}
 */
let consenteeTokenGenerator = undefined;

/**
 * @type {ConsentClient | undefined}
 */
let consenterClient = undefined;

/**
 * @type {PersonalTokenGenerator | undefined}
 */
let consenterTokenGenerator = undefined;

/**
 * @type {MaskinportenClient | undefined}
 */
let lookupClient = undefined;

/**
 * The organizations that receive, and therefore hold, the consents.
 *
 * @param {string} env - Environment, e.g. "yt01".
 * @returns {Array<{orgNo: string}>} The consentee organizations.
 */
export function getConsenteeOrgs(env) {
    const res = http.get(`${TESTDATA_BASE_URL}/consentee-orgs/${env}.csv`, {
        tags: { action: "fetch-test-data" },
    });

    return parseCsvData(res.body);
}

/**
 * The persons that approve the consents.
 *
 * @param {string} env - Environment, e.g. "yt01".
 * @returns {Array<{ssn: string, partyUuid: string}>} The consenter persons.
 */
export function getConsenterPersons(env) {
    const res = http.get(`${TESTDATA_BASE_URL}/consenter-persons/${env}.csv`, {
        tags: { action: "fetch-test-data" },
    });

    return parseCsvData(res.body);
}

/**
 * Consents generated by an earlier run of testdataGeneration/consent-data.js,
 * for the lookup test to look up.
 *
 * @param {string} env - Environment, e.g. "yt01".
 * @returns {Array<{Pid: string, Org: string, ConsentId: string}>} Consents to look up.
 */
export function getLookupConsents(env) {
    const res = http.get(`${TESTDATA_BASE_URL}/lookup/${env}.csv`, {
        tags: { action: "fetch-test-data" },
    });

    return parseCsvData(res.body);
}

/**
 * Creates and caches the client for acting as the organization a consent is given
 * to.
 *
 * Built once per VU and reused across its iterations. The token generators cache
 * tokens per instance, so building them per iteration refetches every token from
 * the token generator service each time.
 *
 * The organization changes per iteration, so its options are swapped with
 * setTokenGeneratorOptions rather than by building a new generator. The cache is
 * keyed on the options, so each organization still gets its own cached token.
 *
 * The token carries the read scope alongside the write scope, which is what lets
 * a test confirm the consent request it made was accepted.
 *
 * @returns {[EnterpriseClient, EnterpriseTokenGenerator]} The client, and the generator whose organization is swapped per iteration.
 */
export function getConsenteeClient() {
    if (consenteeClient === undefined) {
        consenteeTokenGenerator = new EnterpriseTokenGenerator(
            getConsenteeTokenOpts(),
        );

        consenteeClient = new EnterpriseClient(__ENV.BASE_URL, consenteeTokenGenerator);
    }

    return [consenteeClient, consenteeTokenGenerator];
}

/**
 * Creates and caches the client for acting as the person giving a consent.
 *
 * Handling a consent request is what the person does in the portal, so it goes
 * through the bff rather than the enterprise api the organization calls. That is
 * a different host, which is why this needs AM_UI_BASE_URL and the consentee
 * client does not.
 *
 * @returns {[ConsentClient, PersonalTokenGenerator]} The client, and the generator whose person is swapped per iteration.
 */
export function getConsenterClient() {
    if (consenterClient === undefined) {
        consenterTokenGenerator = new PersonalTokenGenerator(
            getConsenterTokenOpts(),
        );

        consenterClient = new ConsentClient(__ENV.AM_UI_BASE_URL, consenterTokenGenerator);
    }

    return [consenterClient, consenterTokenGenerator];
}

/**
 * Creates and caches the client the lookup test reads with.
 *
 * Kept apart from getClients because it needs its own token: the lookup is what
 * Maskinporten does on behalf of the consumer, so it asks for the Maskinporten
 * consent scope and nothing else.
 *
 * The token carries no organization number, matching how the endpoint is called
 * in practice.
 *
 * @returns {MaskinportenClient} The client the lookup test reads with.
 */
export function getLookupClient() {
    if (lookupClient === undefined) {
        const tokenGenerator = new EnterpriseTokenGenerator(
            new EnterpriseTokenBuilder()
                .withEnvironment(__ENV.ENVIRONMENT)
                .withTtl(3600)
                .withScopes(CreateScopeString([AltinnScopes.MASKINPORTEN.CONSENT.READ]))
                .build(),
        );

        lookupClient = new MaskinportenClient(__ENV.BASE_URL, tokenGenerator);
    }

    return lookupClient;
}

/**
 * Token options for acting as the organization a consent is given to.
 *
 * Called without an organization number to build the generator, and with one per
 * iteration to point it at the organization that iteration drew.
 *
 * @param {string} [orgNo] - The consentee organization, or undefined to leave the token without one.
 * @returns {object} Options to hand to setTokenGeneratorOptions.
 */
export function getConsenteeTokenOpts(orgNo = undefined) {
    const builder = new EnterpriseTokenBuilder()
        .withEnvironment(__ENV.ENVIRONMENT)
        .withTtl(3600)
        .withScopes(CreateScopeString([
            AltinnScopes.CONSENTREQUESTS.WRITE,
            AltinnScopes.CONSENTREQUESTS.READ,
        ]));

    if (orgNo !== undefined) {
        builder.withOrganizationNumber(orgNo);
    }

    return builder.build();
}

/**
 * Token options for acting as the person giving a consent.
 *
 * Called without a party uuid to build the generator, and with one per iteration
 * to point it at the person that iteration drew.
 *
 * @param {string} [partyUuid] - The consenter, or undefined to leave the token without one.
 * @returns {object} Options to hand to setTokenGeneratorOptions.
 */
export function getConsenterTokenOpts(partyUuid = undefined) {
    const builder = new PersonalTokenBuilder()
        .withEnvironment(__ENV.ENVIRONMENT)
        .withTtl(3600)
        .withScopes(CreateScopeString([AltinnScopes.PORTAL.ENDUSER]));

    if (partyUuid !== undefined) {
        builder.withPartyUuid(partyUuid);
    }

    return builder.build();
}

/**
 * Builds the consent request one iteration asks for.
 *
 * The id is generated by the caller rather than here, since the caller needs it
 * both to create the consent request and to look the consent up afterwards.
 *
 * @param {object} options - The parties and the id this consent request is for.
 * @param {string} options.consentId - The id the consent gets.
 * @param {string} options.from - Party urn of the person giving the consent.
 * @param {string} options.to - Party urn of the organization receiving it.
 * @returns {ConsentRequestDto} The consent request payload.
 */
export function createConsentRequest({ consentId, from, to }) {
    return new ConsentRequestBuilder()
        .WithId(consentId)
        .WithFrom(from)
        .WithTo(to)
        .WithValidTo(consentValidTo())
        .WithConsentRights(consentRights())
        .WithRedirectUrl(REDIRECT_URL)
        .Build();
}

/**
 * Builds the body that looks a consent up the way Maskinporten does.
 *
 * @param {object} options - The consent to look up.
 * @param {string} options.consentId - Id of the consent.
 * @param {string} options.from - Party urn of the person who gave the consent.
 * @param {string} options.to - Party urn of the organization that received it.
 * @returns {ConsentLookupRequest} The lookup payload.
 */
export function createConsentLookupRequest({ consentId, from, to }) {
    return new ConsentLookupRequestBuilder()
        .withId(consentId)
        .withFrom(from)
        .withTo(to)
        .build();
}

/**
 * The rights every generated consent covers.
 *
 * @returns {Array<ConsentRightDto>} The consent rights.
 */
export function consentRights() {
    return [
        {
            action: ["consent"],
            resource: [
                { type: "urn:altinn:resource", value: CONSENT_RESOURCE },
            ],
            metaData: { inntektsaar: "2026" },
        },
    ];
}

/**
 * Party urn of a person, as the consent api identifies the one giving a consent.
 *
 * @param {string} ssn - National identity number.
 * @returns {string} The party urn.
 */
export function personUrn(ssn) {
    return `urn:altinn:person:identifier-no:${ssn}`;
}

/**
 * Party urn of an organization, as the consent api identifies the one receiving a
 * consent.
 *
 * @param {string} orgNo - Organization number.
 * @returns {string} The party urn.
 */
export function organizationUrn(orgNo) {
    return `urn:altinn:organization:identifier-no:${orgNo}`;
}

/**
 * `validTo` for generated consents.
 *
 * Far enough out that the consents, and the lookup data derived from them, do not
 * go stale between runs.
 *
 * @returns {string} Iso timestamp roughly four years from now.
 */
export function consentValidTo() {
    return new Date(Date.now() + 36500 * 60 * 60 * 1000).toISOString();
}
