import { group } from "k6";

import { randomItem } from "../../../../common-imports.js";
import { getOptions, requireEnv } from "../../../../helpers.js";
import { LookupConsent } from "../../../building-blocks/access-management/resource-owner/maskinporten/index.js";
import { ConsentDomainChecks } from "../../../domain-checks/access-management/consent.js";
import { createConsentLookupRequest, getLookupClient, getLookupConsents, organizationUrn, personUrn } from "./commons.js";

const lookupConsentLabel = { step: "Lookup Consent" };

export const options = getOptions([lookupConsentLabel]);

export function setup() {
    requireEnv(["ENVIRONMENT", "BASE_URL"]);

    return getLookupConsents(__ENV.ENVIRONMENT);
}

/**
 * Test: looking up already granted consents the way Maskinporten does.
 *
 * Reads consents generated by testdataGeneration/consent-data.js, so it only runs
 * where that data has been generated and committed.
 *
 * @param {Array<{Pid: string, Org: string, ConsentId: string}>} rows Consents to look up.
 */
export default function (rows) {
    const lookupClient = getLookupClient();

    const row = randomItem(rows);

    group("As Maskinporten, I can look up a granted consent", function () {
        const lookupRequest = createConsentLookupRequest({
            consentId: row.ConsentId,
            from: personUrn(row.Pid),
            to: organizationUrn(row.Org),
        });

        const consent = LookupConsent(lookupClient, lookupRequest, lookupConsentLabel);

        ConsentDomainChecks.CheckConsentResponse(consent, "LookupConsent");
    });
}

// add the custom reporting for this test to the default summary
export { handleSummary } from "../../../../common-imports.js";
