apiVersion: batch/v1
kind: CronJob
metadata:
  name: playwright
  namespace: platform
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            testrunner: playwright
            azure.workload.identity/use: "true"
        spec:
          restartPolicy: Never
          serviceAccountName: playwright-reporter-sa
          nodeSelector:
            kubernetes.azure.com/scalesetpriority: spot
            spot8cpu28gbmem: "true"
          resources:
            requests:
              cpu: 2
              memory: 2000Mi
          tolerations:
            - effect: NoSchedule
              key: kubernetes.azure.com/scalesetpriority
              operator: Equal
              value: spot
          containers:
            - name: playwright
              image: altinnplatformvalidationtests.azurecr.io/custom-playwright-runner:altinn-access-management-frontend-v3
              volumeMounts:
                - name: swa-config
                  mountPath: /etc/swa-config
                  readOnly: true
              envFrom:
                - secretRef:
                    name: am-ui-playwright-env
              env:
                - name: APP_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: swa-app-token
                      key: APP_TOKEN
                - name: SUBSCRIPTION_ID
                  valueFrom:
                    secretKeyRef:
                      name: swa-app-token
                      key: SUBSCRIPTION_ID
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: slack-test
                      key: SLACK_WEBHOOK_URL
                - name: REPORT_URL
                  valueFrom:
                    secretKeyRef:
                      name: swa-app-token
                      key: REPORT_URL

                - name: PLAYWRIGHT_HTML_OPEN
                  value: "never"

                - name: PLAYWRIGHT_HTML_ATTACHMENTS_BASE_URL
                  value: "https://jolly-plant-033965703.7.azurestaticapps.net/api/getreport/"

                - name: PLAYWRIGHT_JUNIT_OUTPUT_NAME
                  value: "test-results.xml"
          volumes:
            - name: swa-config
              secret:
                secretName: swa-config
