import http from "k6/http";

import {
    ChangeRequestSystemUserClient,
    RegisterSystemRequestBuilder,
    RequestSystemUserClient,
    SystemRegisterClient,
    SystemUserClient,
} from "../../../clients/authentication/v2/index.js";
import { EnterpriseTokenBuilder, EnterpriseTokenGenerator, PersonalTokenBuilder, PersonalTokenGenerator, uuidv4 } from "../../../common-imports.js";
import { parseCsvData, requireEnv } from "../../../helpers.js";
import { AltinnScopes, CreateScopeString } from "../../../scopes.js";

/**
 * The vendor these tests act as. Owns the registered systems they create.
 */
const SYSTEM_OWNER = "713431400";

/**
 * Every system registered by these tests allows the same redirect url.
 */
const REDIRECT_URL = "https://digdir.no";

/**
 * Fetches the customers the tests act on behalf of, one per VU.
 *
 * Call from setup(). The result is handed to the default function as its
 * argument, so a test indexes it with vu.idInTest - 1.
 *
 * @returns {object[]} Parsed customer rows.
 */
export function fetchCustomers() {
    requireEnv(["ENVIRONMENT", "BASE_URL"]);

    const res = http.get(
        `https://raw.githubusercontent.com/Altinn/altinn-platform-validation-tests/refs/heads/main/K6/testdata/authentication/data-${__ENV.ENVIRONMENT}-all-customers.csv`,
        { tags: { action: "fetch-test-data" } },
    );

    return parseCsvData(res.body);
}

/**
 * Builds the right that grants access to a single resource.
 *
 * @param {string} resource - Resource identifier.
 * @returns {object} A right the system register and the requests understand.
 */
export function resourceRight(resource) {
    return {
        resource: [
            {
                value: resource,
                id: "urn:altinn:resource",
            },
        ],
    };
}

/**
 * Builds the identifiers, clients and system registration a system user test needs.
 *
 * Keeps the wiring out of the test files, so opening one shows what is being
 * tested rather than how the clients were built. The system is registered with
 * every right in registeredRights, which lets a test grant a subset up front and
 * ask for the rest later.
 *
 * @param {object} customer - The customer row this VU acts on behalf of.
 * @param {object} options - Test specific parts of the setup.
 * @param {string} options.systemNamePrefix - Prefix for the generated system name, so systems are traceable to the test that made them.
 * @param {object[]} options.registeredRights - Every right the system is registered with.
 * @param {string[]} [options.additionalVendorScopes] - Scopes this test needs beyond the shared vendor set.
 * @returns {object} Identifiers, the registration payload, and vendor and approver clients.
 */
export function createSystemUserTestContext(customer, {
    systemNamePrefix,
    registeredRights,
    additionalVendorScopes = [],
}) {
    const systemName = `${systemNamePrefix}${uuidv4()}`;
    const systemId = `${SYSTEM_OWNER}_${systemName}`;
    const clientId = uuidv4();
    const externalRef = uuidv4();

    const vendorScopes = CreateScopeString([
        AltinnScopes.AUTHENTICATION.SYSTEMREGISTER.WRITE,
        AltinnScopes.AUTHENTICATION.SYSTEMUSER.REQUEST.WRITE,
        AltinnScopes.AUTHENTICATION.SYSTEMUSER.REQUEST.READ,
        AltinnScopes.AUTHORIZATION.AUTHORIZE,
        ...additionalVendorScopes,
    ]);

    const vendorTokenGenerator = new EnterpriseTokenGenerator(
        new EnterpriseTokenBuilder()
            .withEnvironment(__ENV.ENVIRONMENT)
            .withTtl(3600)
            .withScopes(vendorScopes)
            .withOrganizationNumber(SYSTEM_OWNER)
            .build(),
    );

    // The approver acts as the customer, which is a person rather than the vendor.
    const approverTokenGenerator = new PersonalTokenGenerator(
        new PersonalTokenBuilder()
            .withEnvironment(__ENV.ENVIRONMENT)
            .withTtl(3600)
            .withScopes(CreateScopeString([AltinnScopes.PORTAL.ENDUSER]))
            .withUserId(customer.userId)
            .withPartyUuid(customer.userPartyUuid)
            .build(),
    );

    const registerSystemRequest = new RegisterSystemRequestBuilder()
        .withId(systemId)
        .withVendor(`0192:${SYSTEM_OWNER}`)
        .withName({
            en: systemName,
            nb: systemName,
            nn: systemName,
        })
        .withDescription({
            en: "This is auto generated by an integration test. Some data is randomized, but some is not - like this description",
            nb: "Integrasjonstest. Noe er randomisert her, men mye blir likt.",
            nn: "integrasjonstest på nynorsk. Noe er randomisert her, men mye blir likt.",
        })
        .withRights(registeredRights)
        .withClientId([clientId])
        .withVisibility(false)
        .withAllowedRedirectUrls([REDIRECT_URL])
        .build();

    return {
        systemOwner: SYSTEM_OWNER,
        systemId,
        systemName,
        clientId,
        externalRef,
        redirectUrl: REDIRECT_URL,
        registerSystemRequest,
        vendor: {
            systemRegisterClient: new SystemRegisterClient(__ENV.BASE_URL, vendorTokenGenerator),
            requestSystemUserClient: new RequestSystemUserClient(__ENV.BASE_URL, vendorTokenGenerator),
            changeRequestClient: new ChangeRequestSystemUserClient(__ENV.BASE_URL, vendorTokenGenerator),
            systemUserClient: new SystemUserClient(__ENV.BASE_URL, vendorTokenGenerator),
        },
        approver: {
            requestSystemUserClient: new RequestSystemUserClient(__ENV.BASE_URL, approverTokenGenerator),
            changeRequestClient: new ChangeRequestSystemUserClient(__ENV.BASE_URL, approverTokenGenerator),
        },
    };
}
