name: Cleanup Operator - Tests

on:
  pull_request:
    paths:
      - "operators/cleaner/**"

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./operators/cleaner

    steps:
      - name: Clone the code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: operators/cleaner/go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
