name: Detect New Swagger Versions

on:
  schedule:
    # Every Monday at 07:00 UTC
    - cron: "0 7 * * 1"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: helpers/detect-new-swagger-versions/go.mod
          cache-dependency-path: helpers/detect-new-swagger-versions/go.sum

      - name: Check Swagger documents
        id: detect-swagger
        continue-on-error: true
        working-directory: helpers/detect-new-swagger-versions
        run: |
          go build .
          chmod +x ./detect-new-swagger-versions
          set +e
          ./detect-new-swagger-versions
          exit_code=$?
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"

      - name: Notify Slack
        if: ${{ steps.detect-swagger.outputs.exit_code == '2' }}
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: ":warning: New Swagger documentation detected.\n<https://github.com/Altinn/altinn-platform-validation-tests/actions/workflows/detect-new-swagger-docs.yml|View workflow>"

      - name: Fail on detection error
        if: ${{ steps.detect-swagger.outputs.exit_code == '1' }}
        run: exit 1
