name: "Playwright AT23 Tests"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "playwright/**"

run-name: "AT23 tests"

concurrency:
  group: "playwright-at23-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

permissions:
  contents: "read"

jobs:
  at23-tests:
    runs-on: "ubuntu-latest"
    environment: "dev"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"

      - name: "Use Node.js"
        uses: "actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f"
        with:
          node-version: "24.x"

      - name: "Dependencies"
        working-directory: "playwright"
        run: "npm install"

      - name: "Install Playwright browsers"
        working-directory: "playwright"
        run: "npx playwright install --with-deps"

      - name: "Run AT23 tests"
        working-directory: "playwright"
        env:
          TEST_IDP_PASSWORD: ${{ secrets.TEST_IDP_PASSWORD }}
        run: "npm run test:at23"
