name: Auth - run k6 breakpoint tests

on:
  push:
  workflow_dispatch:
    inputs:
      configFilePath:
        description: "Configuration file for the test runs"
        required: true
        default: "conf/auth-break.yaml"

      testName:
        type: choice
        description: "The test to run"
        options:
          - post-consent
          - get-authorized-parties-org
          - get-authorized-parties-sysuser
          - get-authorized-parties-user

      target_vus:
        description: "The target VUs to reach"
        required: false
        # default: 100

      duration:
        description: "How long should it take to reach the target_vus"
        required: false
        # default: 10m

      abortOnFail:
        description: "Should the test run stop as soon as the threshold fails"
        type: choice
        required: false
        options:
          - ""
          - "true"
          - "false"

      commandLineArgs:
        description: "Command line arguments to pass to the k6 run command"
        required: false
        default: ""

  schedule:
    - cron: "0 08 * * 1"
    - cron: "0 10 * * 1"
    - cron: "0 12 * * 1"
    - cron: "0 14 * * 1"

permissions:
  id-token: write
  contents: read

jobs:
  k6-breakpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process CLI args
        shell: bash
        run: |
          TARGET_VUS="${TARGET_VUS:-}"
          DURATION="${DURATION:-}"
          ABORT_ON_FAIL="${ABORT_ON_FAIL:-}"
          COMMAND_LINE_ARGS="${COMMAND_LINE_ARGS:-}"

          OUTPUT=""

          if [ -n "$TARGET_VUS" ]; then
            OUTPUT="$OUTPUT --env BREAKPOINT_STAGE_TARGET=$TARGET_VUS"
          fi

          if [ -n "$DURATION" ]; then
            OUTPUT="$OUTPUT --env BREAKPOINT_STAGE_DURATION=$DURATION"
          fi

          if [ -n "$ABORT_ON_FAIL" ]; then
            OUTPUT="$OUTPUT --env BREAKPOINT_STAGE_ABORTONFAIL=$ABORT_ON_FAIL"
          fi

          if [ -n "$COMMAND_LINE_ARGS" ]; then
            OUTPUT="$OUTPUT $COMMAND_LINE_ARGS"
          fi

          # Remove leading whitespace
          OUTPUT=$(echo "$OUTPUT" | sed 's/^[[:space:]]*//')

          # Output the final string
          echo "COMMAND_LINE_ARGS=$OUTPUT" >> $GITHUB_ENV
        env:
          TARGET_VUS: ${{ inputs.target_vus }}
          DURATION: ${{ inputs.duration }}
          ABORT_ON_FAIL: ${{ inputs.abortOnFail }}
          COMMAND_LINE_ARGS: ${{ inputs.commandLineArgs }}

      - name: Check that CLI args are populated correctly
        shell: bash
        run: |
          echo ${{ env.COMMAND_LINE_ARGS }}
